# Generated by Django 4.2.1 on 2023-06-04 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='nane',
            new_name='name',
        ),
    ]
