# Generated by Django 4.2.1 on 2023-07-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_amnetie_cuisine_dietaryoption_diningoption_interior_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='fire_id',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='payment_option',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='payment_option',
            field=models.ManyToManyField(related_name='restaurant_payment', to='restaurants.paymentoption'),
        ),
    ]
